apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
  namespace: argocd
  labels:
    app: argocd-dex-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-dex-server
  template:
    metadata:
      labels:
        app: argocd-dex-server
    spec:
      containers:
      - name: argocd-dex-server
        image: quay.io/argoproj/argocd:v2.12.0